apiVersion: v1
kind: PersistentVolume
metadata:
  name: author-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/aem/author-data