apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: aem-author-deployment
    aem-component: author
  name: aem-author-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aem-author-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: aem-author-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: aem-author-data
            mountPath: /opt/aem/crx-quickstart 
        ports:
#         - containerPort: 4502
         - containerPort: 80
        resources: {}
      volumes:
      - name: aem-author-data
        persistentVolumeClaim:
          claimName: author-pvc
status: {}